version: '3'

services:

  nginx:
    image: nginx
    network_mode: host
    volumes:
      - "./etc_nginx/:/etc/nginx/" # config + ssl
      # - "./html:/usr/share/nginx/html" # fe
      - "./fe/react/radapp/dist:/usr/share/nginx/html" # fe
