version: '3'

services:

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    # ports:
    #   - "16686:16686"
    #   - "14268"
    #   - "14250:14250"
    network_mode: host

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      - jaeger-all-in-one
    command:
      [
        "--config=/etc/otel_collector_config/otel-collector-config.yaml"
      ]
    volumes:
      - ./otel_collector_config:/etc/otel_collector_config
    # ports:
    #   - "4317:4317" # otlp receiver
    network_mode: host
