version: '3'

services:

  postgres:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5432
    # command: [ "postgres", "-c", "log_statement=all" ]
